### ISSUE TITLE
关于该repo的部分建议

### ISSUE THREAD

**Issue by kawashiro-ryofu** [historical-records/996RIP#1]
介于996.icu长时间无人维护，故出现了此储存库。本人意识形态是民主社会主义，对于996这一类事件较为关注，故对此repo提出部分建议。

首先，建议更改当前储存库名为996RIP。相信各位也知道最近拼多多的事件。已经有劳工死于996。

此外，开通本repo的GitHub Pages，内容以CreativeCommons中的协议发布。此外，支持各个开发者克隆此项目并以其账号开通GitHub Pages，以防止无良中国特色互联网企业旗下浏览器的封锁。

最后，希望此repo能够长期更新。在劳动者权益还不能得到保障前，绝不能停止斗争！

**Comment by record00001** [comment]
@kawashiro-ryofu 你好，感谢你的建议。根据你的建议，我已经更改库名。对于GitHub Pages，请问有没有具体的方案或者想法？

**Comment by kawashiro-ryofu** [comment]
> @kawashiro-ryofu 你好，感谢你的建议。根据你的建议，我已经更改库名。对于GitHub Pages，请问有没有具体的方案或者想法？

GitHub pages 其实就相当于把这个储存库做成静态网页网站。本人认为只需要在996.icu储存库的基础上改i18n里面的markdown 文件就好。996.icu的模板貌似是可以把储存库的markdown文件转换为HTML。这个我也没试过，我只是把博客托管在GitHub上面，但你可以试试。

**Comment by record00001** [comment]
> > @kawashiro-ryofu 你好，感谢你的建议。根据你的建议，我已经更改库名。对于GitHub Pages，请问有没有具体的方案或者想法？
> 
> GitHub pages 其实就相当于把这个储存库做成静态网页网站。本人认为只需要在996.icu储存库的基础上改i18n里面的markdown 文件就好。996.icu的模板貌似是可以把储存库的markdown文件转换为HTML。这个我也没试过，我只是把博客托管在GitHub上面，但你可以试试。

我去996.icu库找了下，没有发现对应的html文件，他似乎是部署在其它服务器上。网页功能后面我会加上，用github pages还是其它方式希望看到这条信息的人能提供建议。

**Comment by location-txl** [comment]
在仓库的设置页可以开启Github pages  默认内容选择本仓库的README.md内容

**Comment by record00001** [comment]
@kawashiro-ryofu @TLocation 
github pages和协议都完成了。

**Comment by Stitch-Taotao** [comment]
希望能够制定一个管理流程，包含项目接管流程，人的精力是有限的，当下作者本人可能很有冲劲搞这个项目，但是过了一年两年可能就因为各种原因不会投放这么多精力关注该项目了，这是完全可能发生的事情，因此希望能够有人出面建立一个官方网站，或者其他方式，以及项目管理人的接管流程，不能像[996ICU项目](https://github.com/996icu/996.ICU) 一样死掉。希望看到的各位有能力的人能够有所启发。 为此新提了一个issue： #2
